# This file is @generated by tarina.lang CLI tool
# It is not intended for manual editing.

from tarina.lang.model import LangItem, LangModel


class CompNonebot:
    tab: LangItem = LangItem("comp/nonebot", "tab")
    enter: LangItem = LangItem("comp/nonebot", "enter")
    exit: LangItem = LangItem("comp/nonebot", "exit")
    other: LangItem = LangItem("comp/nonebot", "other")
    timeout: LangItem = LangItem("comp/nonebot", "timeout")
    exited: LangItem = LangItem("comp/nonebot", "exited")


class NbpAlc:
    log_load_global_extensions: LangItem = LangItem("nbp-alc", "log.load_global_extensions")
    log_got_path_ms: LangItem = LangItem("nbp-alc", "log.got_path/ms")
    log_got_path_validate: LangItem = LangItem("nbp-alc", "log.got_path/validate")
    log_discord_ambiguous_command: LangItem = LangItem("nbp-alc", "log.discord_ambiguous_command")
    log_discord_ambiguous_subcommand: LangItem = LangItem("nbp-alc", "log.discord_ambiguous_subcommand")
    log_parse: LangItem = LangItem("nbp-alc", "log.parse")
    error_discord_prefix: LangItem = LangItem("nbp-alc", "error.discord_prefix")
    error_extension_forbid_exclude: LangItem = LangItem("nbp-alc", "error.extension_forbid_exclude")
    error_extension_path_load: LangItem = LangItem("nbp-alc", "error.extension_path_load")
    error_extension_path_invalid: LangItem = LangItem("nbp-alc", "error.extension_path_invalid")
    error_matcher_got_path: LangItem = LangItem("nbp-alc", "error.matcher_got_path")


class NbpAlcBuiltin:
    lang_list: LangItem = LangItem("nbp-alc/builtin", "lang.list")
    lang_switch: LangItem = LangItem("nbp-alc/builtin", "lang.switch")
    lang_locale_missing: LangItem = LangItem("nbp-alc/builtin", "lang.locale_missing")
    lang_locale_timeout: LangItem = LangItem("nbp-alc/builtin", "lang.locale_timeout")
    help_plugin_name_unknown: LangItem = LangItem("nbp-alc/builtin", "help.plugin_name_unknown")
    help_plugin_name: LangItem = LangItem("nbp-alc/builtin", "help.plugin_name")
    help_plugin_id: LangItem = LangItem("nbp-alc/builtin", "help.plugin_id")
    help_plugin_path: LangItem = LangItem("nbp-alc/builtin", "help.plugin_path")
    help_plugin_module: LangItem = LangItem("nbp-alc/builtin", "help.plugin_module")
    help_plugin_version: LangItem = LangItem("nbp-alc/builtin", "help.plugin_version")


class Lang(LangModel):
    comp_nonebot = CompNonebot
    nbp_alc = NbpAlc
    nbp_alc_builtin = NbpAlcBuiltin
