from .segment import At as At
from .segment import File as File
from .segment import AtAll as AtAll
from .segment import Audio as Audio
from .segment import Emoji as Emoji
from .segment import Image as Image
from .segment import Other as Other
from .segment import Reply as Reply
from .segment import Video as Video
from .segment import Voice as Voice
from .segment import Segment as Segment
from .message import UniMessage as UniMessage
