MAPPING = {
    "mirai2": "mirai2",
    "BilibiliLive": "bilibili",
    "Console": "console",
    "Ding": "ding",
    "Discord": "discord",
    "Dodo": "dodo",
    "Feishu": "feishu",
    "Github": "github",
    "Kritor": "kritor",
    "Kaiheila": "kook",
    "Minecraft": "minecraft",
    "Mirai": "mirai",
    "ntchat": "ntchat",
    "OneBot V11": "onebot11",
    "OneBot V12": "onebot12",
    "QQ": "qq",
    "RedProtocol": "red",
    "Tailchat": "tailchat",
    "Telegram": "telegram",
    "Satori": "satori",
}
